// `bcrypt`'s native binding doesn't load on this Windows dev box over a UNC
// path (same class of issue as `sharp` elsewhere in this migration) — mocked
// with the pure-JS, hash-format-compatible `bcryptjs` for THIS TEST ONLY.
// Production code still requires the real `bcrypt`, untouched.
jest.mock('bcrypt', () => require('bcryptjs'));

const bcrypt = require('bcrypt');
const { verifyPassword } = require('../password.utils');

describe('password.utils', () => {
    describe('verifyPassword', () => {
        it('should verify correctly against a legacy PHP-style ($2y$) hash', async () => {
            // bcrypt.hash always produces a $2b$ hash in Node; we rewrite the prefix
            // to simulate a hash originally generated by the PHP system.
            const nativeHash = await bcrypt.hash('minhaSenha123', 10);
            const legacyHash = nativeHash.replace('$2b$', '$2y$');

            await expect(verifyPassword('minhaSenha123', legacyHash)).resolves.toBe(true);
            await expect(verifyPassword('senhaErrada', legacyHash)).resolves.toBe(false);
        });

        it('should verify correctly against a native ($2b$) hash', async () => {
            const nativeHash = await bcrypt.hash('minhaSenha123', 10);
            await expect(verifyPassword('minhaSenha123', nativeHash)).resolves.toBe(true);
            await expect(verifyPassword('senhaErrada', nativeHash)).resolves.toBe(false);
        });
    });
});
